// Code generated by "stringer -type=Stage -trimprefix=Stage"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StageRoll-1]
	_ = x[StagePickUp-2]
	_ = x[StageDrop-3]
	_ = x[StageTurn-4]
	_ = x[StageEndOfGame-5]
}

const _Stage_name = "RollPickUpDropTurnEndOfGame"

var _Stage_index = [...]uint8{0, 4, 10, 14, 18, 27}

func (i Stage) String() string {
	i -= 1
	if i < 0 || i >= Stage(len(_Stage_index)-1) {
		return "Stage(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Stage_name[_Stage_index[i]:_Stage_index[i+1]]
}
